version: 2

multi-ecosystem-groups:
  all:
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    labels:
      - 'changelog:dependencies'
    open-pull-requests-limit: 5

updates:
  - package-ecosystem: "github-actions"
    multi-ecosystem-group: "all"
    patterns:
      - "*"
    directories:
      - "/"
      - "/.github/workflows/*"
    cooldown:
      default-days: 7

  - package-ecosystem: pre-commit
    multi-ecosystem-group: "all"
    patterns:
      - "*"
    directory: "/"
    cooldown:
      default-days: 7
