#!/usr/bin/env bash
# Creates GitHub issues from security scan findings.
# Input: findings.txt with format file|line|rule|severity|message
set -euo pipefail

findings_file="${1:-findings.txt}"
[ -f "$findings_file" ] || exit 0

while IFS='|' read -r file line rule severity message; do
  [ -z "$file" ] && continue
  title="[oblt-aw][security] $rule: $(basename "$file") line $line"
  body="## Security Finding

**Rule:** $rule
**Severity:** $severity
**File:** \`$file\`
**Line:** $line

**Message:** $message

---
*Generated by oblt-aw security detector. Rules: [security-scanning-ruleset](https://github.com/${GITHUB_REPOSITORY}/blob/main/docs/workflows/security-scanning-ruleset.md) (SEC-001–SEC-044, aligned with [observability-robots#3758](https://github.com/elastic/observability-robots/issues/3758)).*"
  gh issue create \
    --title "$title" \
    --body "$body" \
    --label "oblt-aw/detector/security" \
    --repo "${GITHUB_REPOSITORY:?}"
done < "$findings_file"
