#!/usr/bin/env bash
# Creates GitHub issues from security scan findings.
# Input: findings.txt with format file|line|rule|severity|message
set -euo pipefail

findings_file="${1:-findings.txt}"
[ -f "$findings_file" ] || exit 0

while IFS='|' read -r file line rule severity message; do
  [ -z "$file" ] && continue
  title="[oblt-aw][security] $rule: $(basename "$file") line $line"
  body="## Security Finding

**Rule:** $rule
**Severity:** $severity
**File:** \`$file\`
**Line:** $line

**Message:** $message

---
*Generated by oblt-aw security detector. See [security-scanning-ruleset](docs/workflows/security-scanning-ruleset.md) for remediation guidance.*"
  gh issue create --title "$title" --body "$body" --repo "${GITHUB_REPOSITORY:?}"
done < "$findings_file"
