#!/usr/bin/env bash
# Copyright 2026-2027 Elasticsearch B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Creates GitHub issues from security scan findings (one issue per rule / SEC id).
# Input: findings.txt with format file|line|rule|severity|message
set -euo pipefail

findings_file="${1:-findings.txt}"
[ -f "$findings_file" ] || exit 0

scan_date="${SECURITY_SCAN_DATE:-$(date -u +%Y-%m-%d)}"

tmpdir=$(mktemp -d)
body_file=$(mktemp)
trap 'rm -rf "$tmpdir"; rm -f "$body_file"' EXIT

while IFS='|' read -r file line rule severity message || [ -n "${file:-}" ]; do
  [ -z "${file:-}" ] && continue
  printf '%s\n' "${file}|${line}|${severity}|${message}" >> "${tmpdir}/${rule}"
done < "$findings_file"

footer='---
*Generated by oblt-aw security detector. Rules: [security-scanning-ruleset](https://github.com/elastic/oblt-aw/blob/main/docs/workflows/security-scanning-ruleset.md) (SEC-001–SEC-044, aligned with [observability-robots#3758](https://github.com/elastic/observability-robots/issues/3758)).*'

shopt -s nullglob
rule_paths=("${tmpdir}"/*)
[[ ${#rule_paths[@]} -eq 0 ]] && exit 0

while read -r rule_file; do
  [[ -f "$rule_file" ]] || continue
  rule=$(basename "$rule_file")

  count=$(grep -cve '^[[:space:]]*$' "$rule_file" || true)
  [ "${count:-0}" -eq 0 ] && continue

  title="[oblt-aw][security] ${rule} — findings (${scan_date})"

  {
    echo "## Security findings (${rule})"
    echo
    echo "**Analysis date:** ${scan_date}"
    echo "**Occurrences:** ${count}"
    echo
    echo "### Details"
    echo
    idx=0
    while IFS='|' read -r f ln sev msg || [ -n "${f:-}" ]; do
      [ -z "${f:-}" ] && continue
      idx=$((idx + 1))
      echo "${idx}. **\`${f}\`** — line **${ln}** — **${sev}** — ${msg}"
      echo
    done < "$rule_file"
    echo "$footer"
  } >"$body_file"

  gh issue create \
    --title "$title" \
    --body-file "$body_file" \
    --label "oblt-aw/detector/security" \
    --repo "${GITHUB_REPOSITORY:?}"
done < <(printf '%s\n' "${rule_paths[@]}" | LC_ALL=C sort)
