#!/usr/bin/env bash
# Copyright 2026-2027 Elasticsearch B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Creates GitHub issues from security scan findings.
# Input: findings.txt with format file|line|rule|severity|message
set -euo pipefail

findings_file="${1:-findings.txt}"
[ -f "$findings_file" ] || exit 0

while IFS='|' read -r file line rule severity message; do
  [ -z "$file" ] && continue
  title="[oblt-aw][security] $rule: $(basename "$file") line $line"
  body="## Security Finding

**Rule:** $rule
**Severity:** $severity
**File:** \`$file\`
**Line:** $line

**Message:** $message

---
*Generated by oblt-aw security detector. Rules: [security-scanning-ruleset](https://github.com/elastic/oblt-aw/blob/main/docs/workflows/security-scanning-ruleset.md) (SEC-001–SEC-044, aligned with [observability-robots#3758](https://github.com/elastic/observability-robots/issues/3758)).*"
  gh issue create \
    --title "$title" \
    --body "$body" \
    --label "oblt-aw/detector/security" \
    --repo "${GITHUB_REPOSITORY:?}"
done < "$findings_file"
