#!/usr/bin/env python3
# Copyright 2026-2027 Elasticsearch B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""Generate oblt-aw-planned-dispatch.yml for active ingress routes."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import TypedDict

from common import ingress_route_specs_from_registry, load_workflow_registry

INGRESS_ORG_KEY = "obs"


@dataclass(frozen=True)
class PlannedDispatchTarget:
    """Generated dispatch workflow file (branch publish is handled by the ingress workflow)."""

    repo: str
    workflow_file: str


class RouteSpec(TypedDict, total=False):
    workflow: str
    secrets: str
    with_input: str


def _config_dir() -> Path:
    return Path(__file__).resolve().parent.parent / "config"


@lru_cache(maxsize=1)
def load_route_specs(org_key: str = INGRESS_ORG_KEY) -> dict[str, RouteSpec]:
    """Load route specs from ``config/<org-key>/workflow-registry.json``."""
    org_dir = _config_dir() / org_key
    registry = load_workflow_registry(org_dir)
    return ingress_route_specs_from_registry(registry)  # type: ignore[return-value]


def get_route_specs() -> dict[str, RouteSpec]:
    """Cached route specs for the ingress org (default: obs)."""
    return load_route_specs()


def gh_aw_workflow_uses(
    spec: RouteSpec, control_plane_ref: str, *, dispatch_repo: str
) -> str:
    """Literal uses: for a gh-aw-* workflow at the control-plane ref (embedded at generation time)."""
    workflow = spec["workflow"]
    return f"{dispatch_repo}/.github/workflows/{workflow}@{control_plane_ref}"


def _dispatch_job_lines(
    route_id: str,
    spec: RouteSpec,
    control_plane_ref: str,
    *,
    dispatch_repo: str,
) -> list[str]:
    lines = [
        f"  {route_id}:",
        f"    name: Invoke {route_id}",
        f"    uses: {gh_aw_workflow_uses(spec, control_plane_ref, dispatch_repo=dispatch_repo)}",
    ]
    if spec.get("with_input") == "allowed-pr":
        lines.append("    with:")
        lines.append("      allowed-bot-users: ${{ inputs.allowed-pr-authors-csv }}")
    elif spec.get("with_input") == "allowed-issue":
        lines.append("    with:")
        lines.append("      allowed-bot-users: ${{ inputs.allowed-issue-authors-csv }}")
    lines.append("    secrets: inherit")
    return lines


def render_planned_dispatch_workflow(
    route_ids: list[str],
    control_plane_ref: str,
    *,
    dispatch_repo: str = "elastic/oblt-aw",
) -> str:
    """One reusable workflow: one job per planned route with static uses -> gh-aw-*."""
    route_specs = get_route_specs()
    lines = [
        "name: Planned oblt-aw dispatch",
        "",
        f"# Generated by scripts/generate_planned_dispatch.py ({dispatch_repo}).",
        "on:",
        "  workflow_call:",
        "    inputs:",
        "      allowed-pr-authors-csv:",
        "        description: Allowed PR bot users (CSV)",
        "        required: false",
        "        type: string",
        "        default: ''",
        "      allowed-issue-authors-csv:",
        "        description: Allowed issue bot users (CSV)",
        "        required: false",
        "        type: string",
        "        default: ''",
        "    secrets:",
        "      COPILOT_GITHUB_TOKEN:",
        "        required: false",
        "      BUILDKITE_API_TOKEN:",
        "        required: false",
        "",
        "permissions:",
        "  contents: read",
        "",
        "jobs:",
    ]
    for route_id in route_ids:
        if route_id not in route_specs:
            raise KeyError(f"unknown route id: {route_id}")
        lines.extend(
            _dispatch_job_lines(
                route_id,
                route_specs[route_id],
                control_plane_ref,
                dispatch_repo=dispatch_repo,
            )
        )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_routes_json(routes_json: str) -> list[str]:
    """Parse and validate a JSON array of route ids."""
    routes = json.loads(routes_json)
    if not isinstance(routes, list):
        raise SystemExit("--routes-json must be a JSON array")
    route_specs = get_route_specs()
    unknown = [route_id for route_id in routes if route_id not in route_specs]
    if unknown:
        raise SystemExit(f"unknown route ids: {', '.join(unknown)}")
    return routes


def commit_message_for_routes(route_ids: list[str]) -> str:
    """Commit message for the planned dispatch workflow update."""
    return f"chore(dispatch): planned routes {', '.join(route_ids)}"


def write_planned_dispatch_workflow(
    routes_json: str,
    control_plane_ref: str,
    output_path: Path,
    *,
    dispatch_repo: str,
) -> list[str]:
    """Write the planned dispatch workflow file; return route ids (empty list if skipped)."""
    routes = parse_routes_json(routes_json)
    if not routes:
        print("no routes; skipping planned dispatch generation")
        return []

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_planned_dispatch_workflow(
            routes, control_plane_ref, dispatch_repo=dispatch_repo
        ),
        encoding="utf-8",
    )
    print(f"wrote {output_path}")
    return routes


def _parse_target(args: argparse.Namespace) -> PlannedDispatchTarget:
    workflow_file = args.dispatch_workflow
    if not workflow_file.endswith((".yml", ".yaml")):
        raise SystemExit("--dispatch-workflow must end with .yml or .yaml")
    return PlannedDispatchTarget(
        repo=args.dispatch_repo,
        workflow_file=workflow_file,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a planned dispatch workflow for active ingress routes."
    )
    parser.add_argument("--routes-json", required=True)
    parser.add_argument(
        "--control-plane-ref",
        default="main",
        help="Ref for gh-aw-* uses: lines (for example main or a commit SHA)",
    )
    parser.add_argument(
        "--dispatch-repo",
        default="elastic/oblt-aw",
        help="owner/repo for gh-aw-* uses: lines (must match ingress invoke)",
    )
    parser.add_argument(
        "--dispatch-workflow",
        required=True,
        help="Workflow filename under .github/workflows/",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to write the generated workflow YAML",
    )
    parser.add_argument(
        "--commit-message-file",
        help="Write the git commit message to this path when routes are non-empty",
    )
    args = parser.parse_args()
    target = _parse_target(args)
    routes = write_planned_dispatch_workflow(
        args.routes_json,
        args.control_plane_ref,
        Path(args.output),
        dispatch_repo=target.repo,
    )
    if routes and args.commit_message_file:
        Path(args.commit_message_file).write_text(
            commit_message_for_routes(routes) + "\n",
            encoding="utf-8",
        )


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as exc:  # noqa: BLE001
        print(f"generate_planned_dispatch failed: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
