---
name: Issue Triage
on:
  workflow_call:
    secrets:
      COPILOT_GITHUB_TOKEN:
        required: true

permissions:
  actions: read
  contents: read
  discussions: write
  issues: write
  pull-requests: write

jobs:
  issue-triage:
    uses: elastic/ai-github-actions/.github/workflows/gh-aw-issue-triage.lock.yml@main
    secrets:
      COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
